### ISSUE TITLE
Unable to start sharing

### ISSUE THREAD

**Issue by rakyi** [marcellmars/letssharebooks#48]
After clicking on "Start sharing" button I get "Check your internet connection... Try again?", but my internet connection is working. Calibre 2.45 on Debian testing.

I tried running `calibre-debug --gui` but there is no output from [let's share books]. How should I debug this?

**Comment by marcellmars** [comment]
could you please try again (after restarting calibre)?

if it doesn't work:
released plugin has logging shut down.
it's a long story but logging (when enabled) goes into two files:
/tmp/letssharebooks_debug.log
and random temp directory which path gets logged in  /tmp/letssharebooks_debug.log
(short explanation: i had to redirect stdout/stderr for ssh subprocess in order to work on win, osx, linux)

if you clone git repository and in letssharebooks/ you should try:
calibre-customize -b calibreletssharebooks;calibre-debug -g

that should bring /tmp/letssharebooks_debug.log

if you want i can prepare .zip with logging enabled...

**Comment by rakyi** [comment]
Restarting calibre didn't help. Cloned the repo and after `calibre-customize -b calibreletssharebooks;calibre-debug -g` and clicking on "Start sharing" I got the same error. I'm running stock `/etc/ssh/ssh_config`.

tmp/letssharebooks_debug.log:
```
31.12.2015 09:51:13: DEBUG: QT_RUNNING: 5
31.12.2015 09:51:34: INFO: REDIRECTED DEBUG OUTPUT: 

tail -f /tmp/tmpxxV8aF/log/lsb.log

31.12.2015 09:51:51: INFO: RUNNING: 4.0.1, LATEST: 4.0.1
31.12.2015 09:51:51: DEBUG: STARTED LOCAL HTTP SERVER!
31.12.2015 09:51:53: INFO: STATE: ON
31.12.2015 09:52:26: INFO: STATE: SSH_SERVER
31.12.2015 09:52:26: DEBUG: PARSE_LOG! COUNTER: 0
31.12.2015 09:52:40: INFO: STATE: OFF
31.12.2015 09:52:40: INFO: STATE: ON
```


```
$ tail -f /tmp/tmpxxV8aF/log/lsb.log
Started up in 40.70 seconds with 48 books
tail: /tmp/tmpxxV8aF/log/lsb.log: file truncated
OpenSSH_7.1p1 Debian-5, OpenSSL 1.0.2e 3 Dec 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
tail: /tmp/tmpxxV8aF/log/lsb.log: file truncated
```

I'm not that good with python and never used Qt, but I can try adding some print/debug lines to code, if you would tell me where.

**Comment by marcellmars** [comment]
this is strange.. the log doesn't get to this line at all:
debug1: Connecting to memoryoftheworld.org [82.221.106.120] port 722.
debug1: Connection established.

what does it say when you do:
ping ssh.memoryoftheworld.org

could you also try just ssh line:
ssh -T -N -g -C -c arcfour,aes128-cbc,blowfish-cbc -o TCPKeepAlive=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveINterval=60 -o ExitOnForwardFailure=yes -v memoryoftheworld.org -l tunnel -D 8890 -p 722

that should establish a simple tunnel with proxy at port 8890 ..

thank you so much for debugging... (this is very strange thing happening with your instalce...)

**Comment by rakyi** [comment]
```
$ ping ssh.memoryoftheworld.org
PING ssh.memoryoftheworld.org (82.221.106.120) 56(84) bytes of data.
64 bytes from ssh.memoryoftheworld.org (82.221.106.120): icmp_seq=1 ttl=251 time=89.7 ms
64 bytes from ssh.memoryoftheworld.org (82.221.106.120): icmp_seq=2 ttl=251 time=91.3 ms
64 bytes from ssh.memoryoftheworld.org (82.221.106.120): icmp_seq=3 ttl=251 time=90.6 ms
^C
--- ssh.memoryoftheworld.org ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 89.747/90.583/91.330/0.694 ms
```
```
$ ssh -T -N -g -C -c arcfour,aes128-cbc,blowfish-cbc -o TCPKeepAlive=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveINterval=60 -o ExitOnForwardFailure=yes -v memoryoftheworld.org -l tunnel -D 8890 -p 722
OpenSSH_7.1p1 Debian-5, OpenSSL 1.0.2e 3 Dec 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to memoryoftheworld.org [82.221.106.120] port 722.
debug1: Connection established.
debug1: identity file /home/rakyi/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rakyi/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rakyi/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rakyi/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rakyi/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rakyi/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rakyi/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/rakyi/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.1p1 Debian-5
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3 pat OpenSSH_6.6.1* compat 0x04000000
debug1: Authenticating to memoryoftheworld.org:722 as 'tunnel'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client arcfour umac-64-etm@openssh.com zlib@openssh.com
debug1: kex: client->server arcfour umac-64-etm@openssh.com zlib@openssh.com
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:4GTIkWSimJyyF0SLx0JOklpieLQ8xPguGGQb8CWoeqI
debug1: checking without port identifier
Warning: Permanently added '[memoryoftheworld.org]:722,[82.221.106.120]:722' (ECDSA) to the list of known hosts.
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Enabling compression at level 6.
debug1: Authentication succeeded (none).
Authenticated to memoryoftheworld.org ([82.221.106.120]:722).
debug1: Local connections to *:8890 forwarded to remote address socks:0
debug1: Local forwarding listening on 0.0.0.0 port 8890.
debug1: channel 0: new [port listener]
socket: Address family not supported by protocol
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
```

**Comment by marcellmars** [comment]
this ssh line is (almost) the same like one called from calibre plugin. calibre plugin only gets to:
OpenSSH_7.1p1 Debian-5, OpenSSL 1.0.2e 3 Dec 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *

where the same line continues to connect when run from terminal.

having that small chunk in logs says that plugin calls the ssh line but it doesn't connect. i'm running debian and because of that i don't think that ssh_config would be a problem..

do you have any firewall? because it looks like just at the moment calibre (from the perspective of os) tries to make a connection it gets silent.

**Comment by rakyi** [comment]
I see. Well, I didn't install/configure any firewall and according to https://wiki.debian.org/DebianFirewall

> The default Debian installation comes with the program iptables(8), configured to **allow all traffic**.

Any other ideas?

**Comment by marcellmars** [comment]
could you, please, check if the calibre library is well prepared for sharing. in the root directory of calibre library you try to share you should find file: BROWSE_LIBRARY.html
(i think the default for calibre is ~/Calibre Library/)

if you open that file in browser it will load metadata from static/data.js and render the page in a browser pretty much the same like on https://library.memoryoftheworld.org

i can imagine that there is a strange unicode thing in metadata and that stops plugin.. i thought i fixed all of these but it is possible...

**Comment by rakyi** [comment]
There is no BROWSE_LIBRARY.html file in the root directory of calibre library nor anywhere else, except the letssharebooks source directory I cloned. Maybe we are getting somewhere.

**Comment by marcellmars** [comment]
ok. the last commit should print out the book id (before, title and after parsing the calibre's sqlite). hopefully to see what's the book (and its id) which brings trouble here.. please, once again (thanx again ;) git pull and then log files...

also, "Started up in 40.70 seconds with 48 books" from your first debug log shows very long calibre's booting time. the last one from my library: "Started up in 8.77 seconds with 2446 books"

**Comment by rakyi** [comment]
I pulled the latest commit and ran `calibre-customize -b calibreletssharebooks;calibre-debug -g` like before, but there is nothing new in the logs. However, the difference in startup time looks suspicious. Do you have an SSD, by chance? Mine is  HDD.

```
03.01.2016 09:34:13: DEBUG: QT_RUNNING: 5
03.01.2016 09:34:34: INFO: REDIRECTED DEBUG OUTPUT: 

tail -f /tmp/tmp9unkG4/log/lsb.log

03.01.2016 09:34:52: INFO: RUNNING: 4.0.1, LATEST: 4.0.1
03.01.2016 09:34:52: DEBUG: STARTED LOCAL HTTP SERVER!
03.01.2016 09:34:53: INFO: STATE: ON
03.01.2016 09:35:07: INFO: STATE: SSH_SERVER
03.01.2016 09:35:07: DEBUG: PARSE_LOG! COUNTER: 0
03.01.2016 09:35:22: INFO: STATE: OFF
03.01.2016 09:35:22: INFO: STATE: ON
```
```
$ tail -f /tmp/tmp9unkG4/log/lsb.log
Started up in 41.19 seconds with 47 books
tail: /tmp/tmp9unkG4/log/lsb.log: file truncated
OpenSSH_7.1p1 Debian-5, OpenSSL 1.0.2e 3 Dec 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
tail: /tmp/tmp9unkG4/log/lsb.log: file truncated
```

**Comment by marcellmars** [comment]
did you do the calibre-customize.... line from letssharebooks/?
does it say in the terminal where you run calibre-customize -b calibreletssharebooks;calibre-debug -g as a first line:
Plugin updated: [let's share books] (4, 0, 1)

it's strange that it nothing changes there.. also: could you join irc.freenode.net #letssharebooks? maybe it will be faster than this thread... thanx

**Comment by rakyi** [comment]
After some more investigation at #letssharebooks we found out that letssharebooks ssh process took more than 15s timeout to connect, so the timeout value is going to be increased as a result.
