### ISSUE TITLE
QString' object has no attribute 'title'

### ISSUE THREAD

**Issue by supergeante** [marcellmars/letssharebooks#50]
Dear all,

tried the calibre plugin so to be able to join. This is the error i get whille trying to connect.

calibre, version 1.48.0
ERREUR: Exception non gérée: <b>AttributeError</b>:'QString' object has no attribute 'title'

calibre 1.48  isfrozen: False is64bit: False
Linux-3.19.0-32-generic-i686-with-LinuxMint-17.3-rosa Linux ('32bit', 'ELF')
('Linux', '3.19.0-32-generic', '#37~14.04.1-Ubuntu SMP Thu Oct 22 09:37:25 UTC 2015')
Python 2.7.6
Linux: ('LinuxMint', '17.3', 'rosa')
Traceback (most recent call last):
  File "calibre_plugins.letssharebooks.main", line 1517, in chat
AttributeError: 'QString' object has no attribute 'title'

Can you help me on this ? 
Regards,

SPG

**Comment by supergeante** [comment]
Not sure i think it's 32/64 bits related...

**Comment by marcellmars** [comment]
could you try to upgrade calibre first? the latest version is 2.62.0
there was a big change when calibre went from version 1.x.x to 2.x.x with upgrade to PyQt5 from PyQt4.. i'm not sure if i'll be able to maintain both 1.x.x and 2.x.x but if there is a sane reason why someone will stay at the old version i would debug that further...
